// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Todo.Data.Models;

#nullable disable

namespace Todo.Data.Context
{
    public partial class TodoContext : DbContext
    {
        public TodoContext()
        {
        }

        public TodoContext(DbContextOptions<TodoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<Card>(entity =>
            {
                entity.HasKey(e => e.IdCard);

                entity.Property(e => e.AdjuntoNombre).HasMaxLength(255);

                entity.Property(e => e.Color)
                    .HasMaxLength(7)
                    .IsFixedLength(true);

                entity.Property(e => e.Creado).HasColumnType("datetime");

                entity.Property(e => e.CreadoPor).HasMaxLength(255);

                entity.Property(e => e.Descripcion).HasMaxLength(255);

                entity.Property(e => e.Modificado).HasColumnType("datetime");

                entity.Property(e => e.ModificadoPor).HasMaxLength(255);

                entity.Property(e => e.Nombre).HasMaxLength(255);
            });

            modelBuilder.Entity<Estado>(entity =>
            {
                entity.HasKey(e => e.IdEstado);

                entity.Property(e => e.Activo).HasDefaultValueSql("((1))");

                entity.Property(e => e.Creado).HasColumnType("datetime");

                entity.Property(e => e.CreadoPor).HasMaxLength(255);

                entity.Property(e => e.Descripcion).HasMaxLength(255);

                entity.Property(e => e.Modificado).HasColumnType("datetime");

                entity.Property(e => e.ModificadoPor).HasMaxLength(255);

                entity.Property(e => e.Nombre).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}