// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Todo.Data.Models
{
    public partial class Card
    {
        public long IdCard { get; set; }
        public long? IdEstado { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Color { get; set; }
        public DateTime? Creado { get; set; }
        public string CreadoPor { get; set; }
        public DateTime? Modificado { get; set; }
        public string ModificadoPor { get; set; }
        public byte[] Adjunto { get; set; }
    }
}